Update public.yaml

diff --git a/.github/workflows/public.yaml b/.github/workflows/public.yaml
--- a/.github/workflows/public.yaml
+++ b/.github/workflows/public.yaml
@@ -18,11 +18,19 @@ jobs:
         now=$(date +"%Y-%m-%dT%H:%M:%S%:z")
         gh workflow run --repo imjasonh/workflow-private private.yaml --ref main
 
-        num=$(gh run list --repo imjasonh/workflow-private -w private.yaml -e workflow_dispatch --created ">${now}" --json number --jq '.[0].number')
+        num=$(gh run list --repo imjasonh/workflow-private -w private.yaml -e workflow_dispatch --created ">${now}" --json number | jq '.[0].number')
+        if [ -z "$num" ]; then
+          echo "No run found"
+          exit 1
+        fi
         echo "num: $num"
         while true; do
           status=$(gh run list --repo imjasonh/workflow-private -w private.yaml --json number,status | jq --arg num "$num" -r '.[] | select(.number == $num) | .status')
           echo "status: $status"
+          if [ "$status" = "" ]; then
+            echo "Status not found"
+            exit 1
+          fi
           if [ "$status" = "completed" ]; then
             break
           fi
